### PR TITLE
User Story 1 completed

### PR DESCRIPTION
**Pull request by kennonoutlaw**
Hi Falko,

Please review and let me know if there's anything that you would do differently.

### CODE REVIEW

**Comment by falkobuttler** [comment]
The only thing missing here is the "swipe to delete" functionality.

**Comment by kennonoutlaw** [comment]
"Swipe to delete" seems to work fine. If I swipe to the left, the delete
button shows and clicking on it deletes the item from Core Data and out of
the table view. Did I miss part of the requirement?

Thanks.

Kennon

**Comment by kennonoutlaw** [comment]
I forgot to mention that when I did the Master-Detail application, it
provided the swipe to delete functionality out of the box inside of this
method.

- (void)tableView:(UITableView *)tableView commitEditingStyle:(
UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath
*)indexPath

**Comment by falkobuttler** [comment]
ok, I didn't see it. No worries :-)

**Pull request merged**
